[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = { workspace = true }
lib = { workspace = true }
eframe = "0.34"
petgraph = "0.8.3"
rfd = "0.17.2"
egui_extras = "0.34"
egui_code_editor = "0.2.21"
subsecond = "0.7.3"
dioxus-devtools = "0.7.3"
env_logger = "0.11.10"
enum_dispatch = "0.3.13"
