//! The script-facing handles to the borrowed context types.
//!
//! Each class is declared here; its *methods* are generated by
//! `#[utils::dynamic_scoped]` on the corresponding inherent `impl` block, so
//! adding a method to [`DrawContext`] or [`Workspace`] binds it automatically.

use pyo3::prelude::*;

use std::sync::Arc;

use std::borrow::Cow;

use crate::stubs::{StubClass, StubField, StubMethod};
use crate::{
    DrawConstraints, DrawContext, DrawResult, Node, NodeContext, NodeHandle, NodeUid, Workspace,
    messages::{Action, Request, action_for, registered_messages, request_for},
    scripting::{FromDynamic, Scoped, ScopedRef, expired_handle},
};

// ======================================================================
// DrawContext
// ======================================================================

/// A scoped handle to a live [`DrawContext`], valid only for the duration of
/// the synchronous `draw` call it was passed into.
#[pyclass(unsendable, name = "DrawContext")]
pub struct PyDrawContext {
    pub inner: Scoped<DrawContext<'static>>,
}

impl PyDrawContext {
    /// Install a handle over `ctx` for the duration of `f`.
    ///
    /// The handle is invalidated before this returns, so anything the script
    /// stashed away is inert rather than dangling.
    pub fn enter<'py, R>(
        py: Python<'py>,
        ctx: &mut DrawContext<'_>,
        f: impl FnOnce(&Bound<'py, PyDrawContext>) -> R,
    ) -> PyResult<R> {
        // Erase the borrow's lifetime; the handle outlives it only as a null pointer.
        #[allow(clippy::unnecessary_cast)] // the cast changes the lifetime, not the type
        let erased: &mut DrawContext<'static> =
            unsafe { &mut *(ctx as *mut DrawContext<'_>).cast::<DrawContext<'static>>() };
        let obj = Bound::new(
            py,
            PyDrawContext {
                inner: unsafe { Scoped::new(erased) },
            },
        )?;

        let out = f(&obj);
        obj.borrow().inner.invalidate();
        Ok(out)
    }

    /// Run `f` against the live context, or raise if the handle has expired.
    pub fn try_with<R>(&self, f: impl FnOnce(&mut DrawContext<'_>) -> R) -> PyResult<R> {
        self.inner.with(f).ok_or_else(expired_handle)
    }
}

#[pymethods]
impl PyDrawContext {
    /// This node's place in the world, as `DrawContext.node` is in Rust.
    #[getter]
    fn node(&self, py: Python<'_>) -> PyResult<Py<PyNodeContext>> {
        let (ws, id) =
            self.try_with(|ctx| (ctx.node.workspace as *const Workspace, ctx.node.id))?;
        // SAFETY: the workspace is live for this call, and the handle is
        // invalidated when the owning `PyDrawContext` expires.
        Py::new(
            py,
            PyNodeContext {
                workspace: unsafe { ScopedRef::new(&*ws) },
                id,
            },
        )
    }

    /// The constraints this node is being drawn under.
    #[getter]
    fn constraints(&self) -> PyResult<DrawConstraints> {
        self.try_with(|ctx| ctx.constraints)
    }

    /// Whether this handle still refers to a live context.
    #[getter]
    fn live(&self) -> bool {
        self.inner.is_live()
    }

    /**
        Draw `node` under `constraints`, reporting what it took.

        The counterpart of `DrawContext::draw_node`, which takes `&dyn Node` and
        so cannot be bound directly. The only thing it adds is accepting either
        form of child: a `NodeUid` handle draws the node the workspace holds
        (drawing it as a *value* would wrap the handle object itself as a script
        node), and anything else is coerced to a node. Positioning is in the
        constraints, exactly as a Rust layout writes it.
    */
    fn draw_node(
        &self,
        node: Bound<'_, PyAny>,
        constraints: DrawConstraints,
    ) -> PyResult<DrawResult> {
        let child = Child::of(&node)?;
        self.try_with(|ctx| match &child {
            Child::Held(id) => ctx
                .draw_workspace_node(*id, constraints)
                .unwrap_or(DrawResult::Complete { region: None }),
            Child::Value(arc) => ctx.draw_node(&**arc, constraints),
        })
    }

    /**
        Draw `node` over everything else, ignoring this node's bounds.

        The counterpart of `DrawContext::overlay_node`. Clip rectangles are
        intersected down the draw tree, so this is the only way for a script
        node to paint outside the box it was given — a preview that hangs off
        its node, a drag ghost, a popup.
    */
    fn overlay_node(
        &self,
        node: Bound<'_, PyAny>,
        constraints: DrawConstraints,
    ) -> PyResult<DrawResult> {
        let child = Child::of(&node)?;
        self.try_with(|ctx| match &child {
            Child::Held(id) => ctx
                .overlay_workspace_node(*id, constraints)
                .unwrap_or(DrawResult::Complete { region: None }),
            Child::Value(arc) => ctx.overlay_node(&**arc, constraints),
        })
    }
}

/// The two forms a script may pass where a node is expected.
enum Child {
    /// A handle to a node the workspace already holds. Drawing it as a value
    /// would wrap the handle object itself, so it is drawn by id instead.
    Held(NodeUid),
    /// Anything else, coerced into a node.
    Value(Arc<dyn Node>),
}

impl Child {
    fn of(node: &Bound<'_, PyAny>) -> PyResult<Self> {
        match node.extract::<NodeHandle>() {
            Ok(handle) => Ok(Self::Held(handle.0)),
            Err(_) => Ok(Self::Value(<Arc<dyn Node> as FromDynamic>::from_dynamic(
                node,
            )?)),
        }
    }
}

dex_dynamic::__rt::inventory::submit! {
    dex_dynamic::DynamicBinding {
        name: "DrawContext",
        register_python: |m| {
            use pyo3::types::PyModuleMethods;
            m.add_class::<PyDrawContext>()
        },
    }
}

// ======================================================================
// Workspace
// ======================================================================

/// A scoped handle to the live [`Workspace`], for queries and mutations a
/// script issues while it runs.
#[pyclass(unsendable, name = "Workspace")]
pub struct PyWorkspace(pub ScopedRef<Workspace>);

impl PyWorkspace {
    /// Install a handle over `ws` for the duration of `f`, invalidating it
    /// before returning.
    pub fn enter<'py, R>(
        py: Python<'py>,
        ws: &Workspace,
        f: impl FnOnce(&Bound<'py, PyWorkspace>) -> R,
    ) -> PyResult<R> {
        // SAFETY: the handle is invalidated below, before `ws`'s borrow ends.
        let obj = Bound::new(py, PyWorkspace(unsafe { ScopedRef::new(ws) }))?;
        let out = f(&obj);
        obj.borrow().0.invalidate();
        Ok(out)
    }

    /// Run `f` against the live workspace, or raise if the handle has expired.
    pub fn try_with<R>(&self, f: impl FnOnce(&Workspace) -> R) -> PyResult<R> {
        self.0.with(f).ok_or_else(expired_handle)
    }
}

#[pymethods]
impl PyWorkspace {
    /// Whether this handle still refers to a live workspace.
    #[getter]
    fn live(&self) -> bool {
        self.0.is_live()
    }

    /**
        Send `request` to `dest` and return its response.

        `Workspace::send_request` is generic over both the target node and the
        response type, so it cannot be bound directly. Instead every
        `defhandlers!` message is a bound class that registers itself, and the
        instance is matched back to its Rust type here — so every request in the
        codebase is reachable without a per-message binding.

        ```python
        text = ctx.workspace.send_request(node, dex.GetText())
        ```
    */
    fn send_request(
        &self,
        py: Python<'_>,
        dest: NodeHandle,
        request: Bound<'_, PyAny>,
    ) -> PyResult<Py<PyAny>> {
        let ws = self
            .0
            .with(|ws| ws as *const Workspace)
            .ok_or_else(expired_handle)?;
        // SAFETY: the pointer is live for this call; `with` just proved it.
        send_request_py(unsafe { &*ws }, dest.0, &request, py)
    }

    /// Queue `action` against `dest`.
    #[pyo3(signature = (dest, action, description=None))]
    fn submit_action(
        &self,
        dest: NodeHandle,
        action: Bound<'_, PyAny>,
        description: Option<String>,
    ) -> PyResult<()> {
        let entry = action_for(&action).ok_or_else(|| not_a_message(&action, false))?;
        let body = (entry.build)(&action)?;

        let queued = Action {
            dest: dest.0,
            description: description
                .map(Cow::Owned)
                .unwrap_or(Cow::Borrowed(entry.name)),
            body,
        };
        self.try_with(|ws| ws.submit_action_dyn(queued))
    }

    /// The names of every request and action a script may send, for discovery.
    #[staticmethod]
    fn message_names() -> (Vec<&'static str>, Vec<&'static str>) {
        registered_messages()
    }
}

/// Route `request` to `dest` in `ws` and hand the response back to Python.
pub(crate) fn send_request_py(
    ws: &Workspace,
    dest: NodeUid,
    request: &Bound<'_, PyAny>,
    py: Python<'_>,
) -> PyResult<Py<PyAny>> {
    let entry = request_for(request).ok_or_else(|| not_a_message(request, true))?;
    let body = (entry.build)(request)?;

    match ws.send_request_dyn(Request { dest, body }) {
        Some(any) => (entry.respond)(any, py),
        // The node did not answer; indistinguishable from a `None` answer.
        None => Ok(py.None()),
    }
}

/// The error a script sees when it passes something that is not a message.
pub(crate) fn not_a_message(obj: &Bound<'_, PyAny>, is_request: bool) -> PyErr {
    let (requests, actions) = registered_messages();
    let (kind, mut known) = if is_request {
        ("request", requests)
    } else {
        ("action", actions)
    };
    known.sort_unstable();
    let got = obj
        .get_type()
        .name()
        .map(|n| n.to_string())
        .unwrap_or_else(|_| "<unknown>".to_owned());
    pyo3::exceptions::PyTypeError::new_err(format!(
        "expected a {kind} message, got `{got}`; known {kind}s: {}",
        known.join(", ")
    ))
}

dex_dynamic::__rt::inventory::submit! {
    dex_dynamic::DynamicBinding {
        name: "Workspace",
        register_python: |m| {
            use pyo3::types::PyModuleMethods;
            m.add_class::<PyWorkspace>()
        },
    }
}

// ======================================================================
// NodeContext
// ======================================================================

/// A scoped handle to a [`NodeContext`]: what a script-defined node's
/// `handle_action` / `request` handlers receive.
#[pyclass(unsendable, name = "NodeContext")]
pub struct PyNodeContext {
    pub(crate) workspace: ScopedRef<Workspace>,
    pub(crate) id: NodeUid,
}

impl PyNodeContext {
    /// Install a handle over `ctx` for the duration of `f`.
    pub fn enter<'py, R>(
        py: Python<'py>,
        ctx: NodeContext<'_>,
        f: impl FnOnce(&Bound<'py, PyNodeContext>) -> R,
    ) -> PyResult<R> {
        let obj = Bound::new(
            py,
            PyNodeContext {
                // SAFETY: invalidated below, before `ctx`'s borrow ends.
                workspace: unsafe { ScopedRef::new(ctx.workspace) },
                id: ctx.id,
            },
        )?;
        let out = f(&obj);
        obj.borrow().workspace.invalidate();
        Ok(out)
    }
}

#[pymethods]
impl PyNodeContext {
    /// This node's own id.
    #[getter]
    fn id(&self) -> NodeHandle {
        NodeHandle(self.id)
    }

    /// A handle to the workspace, scoped to this same call.
    #[getter]
    fn workspace(&self, py: Python<'_>) -> PyResult<Py<PyWorkspace>> {
        let ws = self
            .workspace
            .with(|ws| ws as *const Workspace)
            .ok_or_else(expired_handle)?;
        // SAFETY: live for this call; the handle expires with this context.
        Py::new(py, PyWorkspace(unsafe { ScopedRef::new(&*ws) }))
    }

    /// Whether this handle still refers to a live context.
    #[getter]
    fn live(&self) -> bool {
        self.workspace.is_live()
    }
}

dex_dynamic::__rt::inventory::submit! {
    dex_dynamic::DynamicBinding {
        name: "NodeContext",
        register_python: |m| {
            use pyo3::types::PyModuleMethods;
            m.add_class::<PyNodeContext>()
        },
    }
}

// ======================================================================
// Stub metadata for the hand-written surface
// ======================================================================

dex_dynamic::__rt::inventory::submit! {
    StubClass {
        name: "DrawContext",
        doc: "A scoped handle to the context a node is being drawn with.",
        fields: &[
            StubField { name: "node", ty: "NodeContext" },
            StubField { name: "constraints", ty: "DrawConstraints" },
            StubField { name: "live", ty: "bool" },
        ],
        constructible: false,
        variants: &[],
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubMethod {
        owner: "DrawContext",
        name: "overlay_node",
        doc: "Draw `node` over everything else, ignoring this node's bounds.",
        params: &[
            StubField { name: "node", ty: "LayoutChild" },
            StubField { name: "constraints", ty: "DrawConstraints" },
        ],
        returns: "DrawResult",
        is_static: false,
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubMethod {
        owner: "DrawContext",
        name: "draw_node",
        doc: "Draw `node` under `constraints`, reporting what it took.",
        params: &[
            StubField { name: "node", ty: "LayoutChild" },
            StubField { name: "constraints", ty: "DrawConstraints" },
        ],
        returns: "DrawResult",
        is_static: false,
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubClass {
        name: "NodeContext",
        doc: "A node's place in the world: its id and its workspace.",
        fields: &[
            StubField { name: "id", ty: "NodeUid" },
            StubField { name: "workspace", ty: "Workspace" },
            StubField { name: "live", ty: "bool" },
        ],
        constructible: false,
        variants: &[],
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubClass {
        name: "Workspace",
        doc: "A scoped handle to the live workspace.",
        fields: &[StubField { name: "live", ty: "bool" }],
        constructible: false,
        variants: &[],
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubMethod {
        owner: "Workspace",
        name: "send_request",
        doc: "Send `request` to `dest` and return its response.",
        params: &[
            StubField { name: "dest", ty: "NodeUid" },
            StubField { name: "request", ty: "Any" },
        ],
        returns: "Any",
        is_static: false,
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubMethod {
        owner: "Workspace",
        name: "submit_action",
        doc: "Queue `action` against `dest`.",
        params: &[
            StubField { name: "dest", ty: "NodeUid" },
            StubField { name: "action", ty: "Any" },
            StubField { name: "description", ty: "Option<String>" },
        ],
        returns: "",
        is_static: false,
    }
}

dex_dynamic::__rt::inventory::submit! {
    StubMethod {
        owner: "Workspace",
        name: "message_names",
        doc: "The names of every request and action a script may send.",
        params: &[],
        returns: "(Vec<String>, Vec<String>)",
        is_static: true,
    }
}
