//! Renders the collected [`stubs`](crate::stubs) metadata as a `dex.pyi`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::stubs::{Position, StubMethod, classes, methods, node_types, python_type_at};

/// The header every generated stub carries, so nobody edits it by hand.
const HEADER: &str = "\
# Generated by `dex`. Do not edit.
#
# This file contains type information for the `dex` module, so an editor's language server can
# provide completion and diagnostics for scripts.

from typing import Any

# Any value a script can hand to something expecting a node: a node class, or a
# primitive that is coerced into one.
NodeLike = Node | str | int | float | bool | None

";

/// Render the whole `dex.pyi`.
pub fn render() -> String {
    let classes = classes();
    let known: BTreeSet<&str> = classes.iter().map(|c| c.name).collect();
    let nodes = node_types();

    // Group methods by the class that owns them.
    let mut by_owner: BTreeMap<&str, Vec<&StubMethod>> = BTreeMap::new();
    for m in methods() {
        by_owner.entry(m.owner).or_default().push(m);
    }

    let mut out = String::from(HEADER);

    for class in &classes {
        // A node type really is a `Node`, so say so rather than making every
        // node-returning script fail to typecheck.
        let base = if nodes.contains(class.name) && class.name != "Node" {
            "(Node)"
        } else {
            ""
        };
        let _ = writeln!(out, "class {}{base}:", class.name);

        let mut body_lines = 0usize;
        if !class.doc.is_empty() {
            let _ = writeln!(out, "    \"\"\"{}\"\"\"", one_line(class.doc));
            body_lines += 1;
        }

        // Fields, readable and assignable from a script.
        for field in class.fields {
            let _ = writeln!(
                out,
                "    {}: {}",
                escape_ident(field.name),
                python_type_at(field.ty, &known, Position::Output)
            );
            body_lines += 1;
        }

        // Enum variants: subclasses when they carry data, attributes when not.
        let unit_only = class.variants.iter().all(|v| v.fields.is_empty());
        for variant in class.variants {
            if unit_only {
                let _ = writeln!(out, "    {}: {}", variant.name, class.name);
            } else {
                let _ = writeln!(out, "    class {}({}):", variant.name, class.name);
                for f in variant.fields {
                    let _ = writeln!(
                        out,
                        "        {}: {}",
                        escape_ident(f.name),
                        python_type_at(f.ty, &known, Position::Input)
                    );
                }
                let params: Vec<String> = variant
                    .fields
                    .iter()
                    .map(|f| {
                        format!(
                            "{}: {}",
                            escape_ident(f.name),
                            python_type_at(f.ty, &known, Position::Input)
                        )
                    })
                    .collect();
                let _ = writeln!(
                    out,
                    "        def __init__(self, {}) -> None: ...",
                    params.join(", ")
                );
            }
            body_lines += 1;
        }

        // The generated constructor, when the type has one.
        if class.constructible && !class.fields.is_empty() {
            let params: Vec<String> = class
                .fields
                .iter()
                .map(|f| {
                    format!(
                        "{}: {}",
                        escape_ident(f.name),
                        python_type_at(f.ty, &known, Position::Input)
                    )
                })
                .collect();
            let _ = writeln!(
                out,
                "    def __init__(self, {}) -> None: ...",
                params.join(", ")
            );
            body_lines += 1;
        } else if class.constructible {
            let _ = writeln!(out, "    def __init__(self) -> None: ...");
            body_lines += 1;
        }

        for m in by_owner.get(class.name).into_iter().flatten() {
            write_method(&mut out, m, &known);
            body_lines += 1;
        }

        if body_lines == 0 {
            let _ = writeln!(out, "    ...");
        }
        out.push('\n');
    }

    // Methods whose owner is declared by hand rather than by `#[dynamic_type]`
    // — the scoped context handles.
    for (owner, ms) in &by_owner {
        if known.contains(owner) {
            continue;
        }
        let _ = writeln!(out, "class {owner}:");
        for m in ms {
            write_method(&mut out, m, &known);
        }
        out.push('\n');
    }

    // The two handles a script is handed as globals: one to write with, one to read.
    let _ = writeln!(out, "ws: WorkspaceActionHandle");
    let _ = writeln!(out, "snapshot: Snapshot");

    out
}

fn write_method(out: &mut String, m: &StubMethod, known: &BTreeSet<&str>) {
    // `Self` is only meaningful next to its owner, which the metadata knows but
    // the type mapper does not. Constructors overwhelmingly return it, so
    // leaving it unresolved would make most of the API `Any`.
    let resolve = |ty: &str, pos: Position| -> String {
        let owned;
        let ty = if ty.trim() == "Self" {
            owned = m.owner.to_owned();
            owned.as_str()
        } else {
            ty
        };
        python_type_at(ty, known, pos)
    };

    let mut params: Vec<String> = Vec::new();
    if !m.is_static {
        params.push("self".to_owned());
    }
    for p in m.params {
        params.push(format!(
            "{}: {}",
            escape_ident(p.name),
            resolve(p.ty, Position::Input)
        ));
    }

    if m.is_static {
        let _ = writeln!(out, "    @staticmethod");
    }
    let _ = writeln!(
        out,
        "    def {}({}) -> {}:",
        m.name,
        params.join(", "),
        resolve(m.returns, Position::Output)
    );
    if m.doc.is_empty() {
        let _ = writeln!(out, "        ...");
    } else {
        let _ = writeln!(out, "        \"\"\"{}\"\"\"", one_line(m.doc));
    }
}

/// Doc comments become a single line, so the stub stays easy to diff.
fn one_line(doc: &str) -> String {
    doc.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
        .replace('\\', "\\\\")
        .replace('"', "'")
}

/// Rust field names that collide with Python keywords.
fn escape_ident(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "None", "True", "False", "class", "def", "lambda", "from", "import", "global", "pass",
        "return", "async", "await", "in", "is", "not", "or", "and", "if", "else", "for", "while",
        "try", "except", "finally", "with", "as", "del", "raise", "yield", "assert", "break",
        "continue", "elif", "nonlocal",
    ];
    if KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_owned()
    }
}
