[package]
name = "workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-clone.workspace = true
egui.workspace = true
rpds = { version = "1.2.1", features = ["serde"] }
serde.workspace = true
slotmap = { version = "1.1.1", features = ["serde"] }
typetag.workspace = true
utils.workspace = true
uuid.workspace = true
