[package]
name = "dex-nodes"
version = "0.1.0"
edition = "2024"

[dependencies]
dex-core.path = "../core/"
dex-dynamic.workspace = true
egui.workspace = true
egui_code_editor = { path = "../../vendored/egui_code_editor/" }
egui_extras = { version = "0.35.0", features = ["image", "svg"] }
pyo3.workspace = true
serde.workspace = true
steel-core.workspace = true
typetag.workspace = true
utils.workspace = true

[dev-dependencies]
eframe = "0.35.0"
